project:
  type: website

website:
  title: "AD688 Summer25 Group Project – Job Market Analysis – Group 4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Introduction.ipynb
        text: Data Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




