project:
  type: website

website:
  title: "Geographic and Remote Work Job Market Analysis - Summ25"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: introduction.qmd
        text: "Introduction"
      - href: data_cleaning_eda.qmd
        text: "Data Cleaning & EDA"
      - href: eda_enhance.qmd
        text: "EDA (Enhanced)"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: nlp_methods.qmd
        text: "NLP Methods"
      - href: ml_analysis.qmd
        text: "ML Methods"
     
format:
  html:
    theme: lumen
    toc: true
    code-fold: true

    
execute:
  execute-dir: project

